services:
  # MySQL Database (used by user-service)
  mysql:
    image: mysql:8.0
    container_name: cloud-kitchen-mysql
    restart: always
    environment:
      MYSQL_DATABASE: cloud_kitchen
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Instance
  redis:
    image: redis:7-alpine
    container_name: cloud-kitchen-redis
    restart: always
    ports:
      - "7999:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
  
  # Service Discovery (Eureka Server)
  eureka-server:
    build:
      context: ./service-discovery
      dockerfile: service-discovery.Dockerfile
    container_name: service_discovery
    restart: always
    env_file:
      - ./service-discovery/service-discovery.env
    ports:
      - "7998:7998"

  # API Gateway
  api_gateway:
    build: 
      context: ./api-gateway
      dockerfile: api-gateway.Dockerfile
    container_name: api-gateway
    restart: always
    env_file:
      - ./api-gateway/api-gateway.env
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      user-service:
        condition: service_started


  user-service:
    build: 
      context: ./user-service
      dockerfile: user-service.Dockerfile
    container_name: user-service
    restart: always
    env_file:
      - ./user-service/user-service.env
    ports:
      - "8001:8001"
    depends_on:
      mysql:
        condition: service_healthy

  restaurant-service:
    build:
      context: ./restaurant-service
      dockerfile: restaurant-service.Dockerfile
    container_name: restaurant-service
    restart: always
    env_file:
      - ./restaurant-service/restaurant-service.env
    ports:
      - "8003:8003"
    depends_on:
      mysql:
        condition: service_healthy


volumes:
  redis-data:
  mysql-data:
